defaults:
  - _self_
  - data: cifar10
  - override hydra/launcher: submitit_slurm

# Need these two below for compatabiity with get_dataset() code 
ngpus: 1
dataroot: "/home/fe/belova/projects/reflected/Reflected-Diffusion/datasets/"
training: 
  batch_size: 1
eval:
  batch_size: 1

# Hopefully we get these params for train/test dataloaders from the data/dataset.yaml
# data:
#   dataset: CIFAR10
#   gen_dataset: CIFAR10
#   image_size: 32
#   random_flip: true

generated_data_path: "/home/fe/belova/projects/reflected/vis/2024.07.09/144145/all_images"

eval_methods:
  IS: true
  FID: true

fid_on_test: true # false

# This arg is needed for FID score
feature: 2048

hydra:
  run:
    dir: eval/${now:%Y.%m.%d}/${now:%H%M%S}
  sweep:
    dir: eval/${now:%Y.%m.%d}/${now:%H%M%S}
    subdir: ${hydra.job.num}
  # launcher:
  #   max_num_timeout: null
  #   timeout_min: null
  #   partition: null
  #   account: null
  #   mem_gb: null
  #   cpus_per_task: null
  #   gpus_per_node: ${ngpus}
  #   constraint: null
